### ISSUE TITLE
Is there a sample capture file available?

### ISSUE THREAD

**Issue by hadrielk** [ros-industrial/packet-simplemessage#14]
Hi,
I'd like to add your Lua script to the test suite in Wireshark (I'm one of the developers).  Do you have a sample pcap/pcapng capture file available?

**Comment by gavanderhoorn** [comment]
I do have some sample capture files, but I haven't made them publicly available. I'll see if I can do that some time this week.

**Comment by gavanderhoorn** [comment]
@hadrielk: I've just pushed a sample capture file to `master`. It doesn't contain all message types, but is a good illustration of typical traffic.

**Comment by hadrielk** [comment]
Cool, I'll add it to the wireshark contribution page. Thanks!
